# Docker compose for development
# version: '3.8'

services:
  gtcrm-app:
    build:
      context: .
      dockerfile: ./docker/php.Dockerfile
    container_name: gtcrm-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./.env:/var/www/.env
      - /var/www/vendor
    environment:
      - APP_ENV=development
    networks:
      - gtcrm-network
    depends_on:
      - gtcrm-postgres
      - gtcrm-elasticsearch

  gtcrm-nginx:
    image: nginx:alpine
    container_name: gtcrm-nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - gtcrm-app
    networks:
      - gtcrm-network        

  gtcrm-node:
    platform: linux/arm64/v8 #this line is optional if you are using Mac Silicon chip (M1/M2/M3)
    build:
      context: .
      dockerfile: ./docker/node.Dockerfile
    # image: my-laravel-node
    container_name: gtcrm-node
    ports:
    - "3000:3000"
    - "5174:5173"
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - /var/www/node_modules
    networks:
      - gtcrm-network

  gtcrm-postgres:
    image: postgres:14-alpine
    container_name: gtcrm-postgres
    ports:
      - 5433:5432
    volumes:
      - gtcrmpostgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_DATABASE}
    networks:
      - gtcrm-network

  gtcrm-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: gtcrm-elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - gtcrmelasticsearch:/usr/share/elasticsearch/data

networks:
  gtcrm-network:
    driver: bridge

volumes:
  gtcrmpostgres:
    driver: local
  gtcrmelasticsearch:
    driver: local