# Docker compose for development
version: '3.8'

services:
  gtcrm-app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.php
    # image: my-laravel-app
    container_name: gtcrm-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./.env:/var/www/.env
    environment:
      - APP_ENV=local
    networks:
      - gtcrm-network

  gtcrm-nginx:
    image: nginx:alpine
    container_name: gtcrm-nginx
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - gtcrm-app
    networks:
      - gtcrm-network        

  gtcrm-node:
    platform: linux/arm64/v8 #this line is optional if you are using Mac Silicon chip (M1/M2/M3)
    build:
      context: .
      dockerfile: ./docker/Dockerfile.node
    # image: my-laravel-node
    container_name: gtcrm-node
    ports:
    - "3000:3000"
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - /var/www/node_modules
    networks:
      - gtcrm-network

  gtcrm-postgres:
    image: postgres:14-alpine
    container_name: gtcrm-node
    ports:
      - 5433:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_DATABASE}
    networks:
      - gtcrm-network

networks:
  gtcrm-network:
    driver: bridge

volumes:
  dbdata:
    driver: local